booking/urls.py
from django.urls import path

from booking.apps import BookingConfig
from booking.views import (
    ReservationCancelView,
    ReservationCreateView,
    ReservationDetailView,
    ReservationsToHistoryListView,
    ReservationsToManageListView,
    ReservationUpdateView,
    TableListView,
)

app_name = BookingConfig.name

urlpatterns = [
    path("tables/", TableListView.as_view(), name="table_list"),
    path("reservation/", ReservationCreateView.as_view(), name="reservation_create"),
    path(
        "<int:pk>/reservation/update/",
        ReservationUpdateView.as_view(),
        name="reservation_update",
    ),
    path(
        "manage_reservations/",
        ReservationsToManageListView.as_view(),
        name="manage_reservations",
    ),
    path(
        "reservations_history/",
        ReservationsToHistoryListView.as_view(),
        name="reservation_history",
    ),
    path("<int:pk>/", ReservationDetailView.as_view(), name="reservation_detail"),
    path(
        "<int:pk>/reservation/cancel/",
        ReservationCancelView.as_view(),
        name="reservation_cancel",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("restaurant/", include("restaurant.urls", namespace="restaurant")),
    path("users/", include("users.urls", namespace="users")),
    path("booking/", include("booking.urls", namespace="booking")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (
    ConfirmationMessageView,
    CustomLoginView,
    UserDetailView,
    UserRegisterView,
    UserUpdateView,
    email_verification,
    UsersListView,
    UserBlockView,
)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "login/",
        CustomLoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path("<int:pk>/user/", UserDetailView.as_view(), name="user_detail"),
    path("<int:pk>/user/update/", UserUpdateView.as_view(), name="user_update"),
    path("confirm/", ConfirmationMessageView.as_view(), name="confirm"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/user/block/", UserBlockView.as_view(), name="user_block"),
]

booking/models.py
from django.db import models

from users.models import User


class Table(models.Model):
    seats_amount = models.PositiveSmallIntegerField(verbose_name="Количество мест")

    def __str__(self):
        return f"Столик № {self.pk}"

    class Meta:
        verbose_name = "Столик"
        verbose_name_plural = "Столики"


class Reservation(models.Model):
    TIME_CHOICES = [
        ("10:00", "10:00"),
        ("11:00", "11:00"),
        ("12:00", "12:00"),
        ("13:00", "13:00"),
        ("14:00", "14:00"),
        ("15:00", "15:00"),
        ("16:00", "16:00"),
        ("17:00", "17:00"),
        ("18:00", "18:00"),
        ("19:00", "19:00"),
        ("20:00", "20:00"),
        ("21:00", "21:00"),
        ("22:00", "22:00"),
        ("23:00", "23:00"),
    ]

    ACTUAL = "Открыта"
    CLOSED = "Закрыта"
    CANCELLED = "Отменена"

    RESERVATION_STATUS_CHOICES = [
        (ACTUAL, "Открыта"),
        (CLOSED, "Закрыта"),
        (CANCELLED, "Отменена"),
    ]
    time = models.CharField(
        max_length=5, choices=TIME_CHOICES, default="10:00", verbose_name="Время"
    )
    table = models.ForeignKey(
        Table, on_delete=models.CASCADE, related_name="tables", verbose_name="Столик"
    )
    date = models.DateField(verbose_name="Дата")
    client_name = models.CharField(
        max_length=35, verbose_name="На чье имя бронь", default="Имя гостя"
    )
    client_phone_number = models.CharField(
        max_length=25,
        verbose_name="Телефон",
        default="Телефон для связи",
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="owner_reservations",
    )
    client_willing = models.TextField(
        verbose_name="Пожелания",
        blank=True,
        null=True,
    )
    status = models.CharField(
        max_length=20,
        choices=RESERVATION_STATUS_CHOICES,
        verbose_name="Статус",
        default="Открыта",
    )

    def __str__(self):
        return f"Бронь на {self.date} в {self.time}"

    class Meta:
        verbose_name = "Бронь"
        verbose_name_plural = "Брони"

booking/forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError

from booking.mixins import StyleFormMixin
from booking.models import Reservation


class ReservationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Reservation
        fields = [
            "table",
            "date",
            "time",
            "client_name",
            "client_phone_number",
            "client_willing",
        ]
        widgets = {
            "date": forms.SelectDateWidget(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        reservation_date = cleaned_data.get("date")
        reservation_time = cleaned_data.get("time")
        reserved_table = cleaned_data.get("table")

        if reservation_date < date.today():
            raise ValidationError(
                "Вы не можете выбрать прошедшую дату для бронирования."
            )

        filtered_reservations = Reservation.objects.filter(
            table=reserved_table,
            date=reservation_date,
            time=reservation_time,
            status="Открыта",
        )
        if filtered_reservations.exists():
            for reservation in filtered_reservations:
                if reservation.owner != self.user:
                    raise ValidationError(
                        "Этот столик уже забронирован в указанные дату и время. "
                        "Пожалуйста, выберите другой столик или время."
                    )

        return cleaned_data

booking/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from booking.forms import ReservationForm
from booking.models import Reservation, Table
from config.settings import EMAIL_HOST_USER
from restaurant.models import Page


class TableListView(ListView):
    model = Table
    template_name = "booking/table_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user
        context["tables"] = Table.objects.all()

        return context


class ReservationCreateView(LoginRequiredMixin, CreateView):
    model = Reservation
    form_class = ReservationForm
    template_name = "booking/reservation_form.html"

    def get_success_url(self, **kwargs):
        return reverse_lazy("booking:reservation_detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        reservation = form.save()
        user = self.request.user
        reservation.owner = user
        reservation.save()
        send_mail(
            subject="Rest-or-run. Бронирование",
            message=f"Уважаемый {user}! Спасибо, что выбрали наш ресторан! Ваша бронь подтверждена, ждем Вас"
            f" {reservation.date} в {reservation.time}!",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["image_path"] = "/static/images/image-22-09-25-07-08.jpg"

        return context


class ReservationUpdateView(LoginRequiredMixin, UpdateView):
    model = Reservation
    form_class = ReservationForm
    template_name = "booking/reservation_form.html"

    def get_success_url(self, **kwargs):
        return reverse_lazy("booking:reservation_detail", kwargs={"pk": self.object.pk})

    def get_object(self, queryset=None):
        reservation = super().get_object(queryset)
        user = self.request.user
        if reservation.owner != user:
            raise PermissionDenied
        return reservation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user
        context["image_path"] = "/static/images/table.jpg"

        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ReservationDetailView(LoginRequiredMixin, DetailView):
    model = Reservation
    template_name = "booking/reservation_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user
        context["tables"] = Table.objects.all()

        return context

    def get_queryset(self):
        return Reservation.objects.filter(owner=self.request.user)


class ReservationsToManageListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = "booking/current_reservations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context

    def get_queryset(self):
        return Reservation.objects.filter(owner=self.request.user, status="Открыта")


class ReservationsToHistoryListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = "booking/reservation_history.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context

    def get_queryset(self):
        user = self.request.user
        if not user.has_perm("users.can_block_user"):
            return Reservation.objects.filter(owner=self.request.user)
        else:
            return Reservation.objects.all()


class ReservationCancelView(LoginRequiredMixin, View):
    def post(self, request, pk):
        reservation = get_object_or_404(Reservation, pk=pk)
        reservation.status = "Отменена"
        reservation.save()
        if request.user.has_perm("users.can_block_user"):
            return redirect("booking:reservation_history")

        return redirect("booking:manage_reservations")

booking/templates/booking/current_reservations.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}Мои Бронирования{% endblock %}</title>
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="display-4">Мои текущие бронирования</p>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for object in object_list %}

    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Бронь на {{ object.time }} {{ object.date }}</h5>
                <h6 class="card-title">Статус: {{ object.status }}</h6>

                <a href="{% url 'booking:reservation_detail' object.pk %}" class="card-link">Просмотр брони</a>
                <a href="{% url 'booking:reservation_history' %}" class="card-link">В историю бронирований</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if not object_list %}
        <h5 class="card-title">У Вас нет текущих бронирований. <a href="{% url 'booking:reservation_create' %}" class="card-link">Нажмите для создания брони</a></h5>
    {% endif %}

</div>
{% endblock %}

booking/templates/booking/reservation_detail.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}Просмотр брони{% endblock %}</title>
{% block content %}
<div class="card">
    <div class="card-header">
        Бронь на {{ object.time }} {{ object.date }}
    </div>
    <div class="card-body">
        <h5 class="card-title">Дата: {{ object.date }}</h5>
        <p class="card-text"> Столик № {{ object.table.pk }}</p>
        <p class="card-text"> Количество мест: {{ object.table.seats_amount }}</p>
        <p class="card-text"> Время бронирования: {{ object.time }}</p>
        <p class="card-text"> Контактный телефон: {{ object.client_phone_number }}</p>
        <p class="card-text"> Бронь на имя: {{ object.client_name }}</p>
        <p class="card-text"> Пожелания: {{ object.client_willing }}</p>
        <p class="card-text"> Статус: {{ object.status }}</p>
        <a class="card-link" href="{% url 'booking:manage_reservations' %}">Мои текущие бронирования</a>
        <a class="card-link" href="{% url 'booking:reservation_history' %}">История бронирований</a>

        {% if object.status == "Открыта" %}
        <a class="card-link link-outline-danger" href="{% url 'booking:reservation_update' object.pk %}">Редактировать</a>
        <form action="{% url 'booking:reservation_cancel' object.pk %}" method="post">
            {% csrf_token %}
            <button type="submit">Отменить бронь</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

booking/templates/booking/reservation_form.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}Новая бронь{% endblock %}</title>
{% block content %}
<div class="card mb-3" style="max-width: 1000px;">
    <div class="row g-2">
        <div class="col-md-5">
            <img src="{{ MEDIA_URL }}{{ image_path }}" class="img-fluid rounded-start">
        </div>
        <div class="col-lg-3 col-md-6 col-sm-16">
            <h2>Бронь</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                {% if object %}
                <a href="{% url 'booking:reservation_detail' object.pk %}" class="btn btn-secondary">Отмена</a>
                {% else %}
                <a href="{% url 'booking:table_list' %}" class="btn btn-secondary">Отмена</a>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

booking/templates/booking/reservation_history.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}История бронирований{% endblock %}</title>
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="display-4">История бронирований</p>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for object in object_list %}

    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Бронь на {{ object.time }} {{ object.date }}</h5>
                <h3 class="card-title">{{ object.table }}</h3>
                <h6 class="card-title">Статус: {{ object.status }}</h6>
                {% if not "users.can_block_user" in perms %}
                    <a href="{% url 'booking:reservation_detail' object.pk %}" class="card-link">Просмотр брони</a>
                {% elif "users.can_block_user" in perms and object.status == "Открыта" %}
                <form action="{% url 'booking:reservation_cancel' object.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Отменить бронь</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% if not object_list %}
        <h5 class="card-title">Ваша история бронирований пока пуста. <a href="{% url 'booking:reservation_create' %}" class="card-link">Нажмите для создания брони</a></h5>
    {% endif %}
</div>
{% endblock %}

booking/templates/booking/table_list.html
{% extends 'restaurant/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Схема зала</h1>
</div>

 <div class="row row-cols-1 row-cols-md-3 g-4">
 {% for object in object_list %}
 <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ object }}</h5>
        <p class="card-text">Количество мест: {{ object.seats_amount }}</p>
      </div>
    </div>
  </div>
 {% endfor %}



</div>













{% endblock %}