booking/urls.py
from django.urls import path

from booking.apps import BookingConfig
from booking.views import (
    ReservationCancelView,
    ReservationCreateView,
    ReservationDetailView,
    ReservationsToHistoryListView,
    ReservationsToManageListView,
    ReservationUpdateView,
    TableListView,
)

app_name = BookingConfig.name

urlpatterns = [
    path("tables/", TableListView.as_view(), name="table_list"),
    path("reservation/", ReservationCreateView.as_view(), name="reservation_create"),
    path(
        "<int:pk>/reservation/update/",
        ReservationUpdateView.as_view(),
        name="reservation_update",
    ),
    path(
        "manage_reservations/",
        ReservationsToManageListView.as_view(),
        name="manage_reservations",
    ),
    path(
        "reservations_history/",
        ReservationsToHistoryListView.as_view(),
        name="reservation_history",
    ),
    path("<int:pk>/", ReservationDetailView.as_view(), name="reservation_detail"),
    path(
        "<int:pk>/reservation/cancel/",
        ReservationCancelView.as_view(),
        name="reservation_cancel",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("restaurant/", include("restaurant.urls", namespace="restaurant")),
    path("users/", include("users.urls", namespace="users")),
    path("booking/", include("booking.urls", namespace="booking")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path

from restaurant.apps import RestaurantConfig
from restaurant.views import SectionDetailView

app_name = RestaurantConfig.name

urlpatterns = [
    path("section/<int:pk>/", SectionDetailView.as_view(), name="section_detail"),
]

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (
    ConfirmationMessageView,
    CustomLoginView,
    UserDetailView,
    UserRegisterView,
    UserUpdateView,
    email_verification,
    UsersListView,
    UserBlockView,
)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "login/",
        CustomLoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path("<int:pk>/user/", UserDetailView.as_view(), name="user_detail"),
    path("<int:pk>/user/update/", UserUpdateView.as_view(), name="user_update"),
    path("confirm/", ConfirmationMessageView.as_view(), name="confirm"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/user/block/", UserBlockView.as_view(), name="user_block"),
]

restaurant/models.py
from django.db import models


class Page(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название страницы")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"


class Section(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название раздела")
    title = models.CharField(
        max_length=50, verbose_name="Заголовок на странице", blank=True, null=True
    )
    image = models.ImageField(
        upload_to="photos/",
        verbose_name="Изображение на странице",
        blank=True,
        null=True,
    )
    page = models.ForeignKey(
        Page,
        verbose_name="Страница",
        on_delete=models.CASCADE,
        related_name="page_sections",
    )
    content = models.TextField(verbose_name="Текст на странице", blank=True, null=True)
    epigraph = models.TextField(
        verbose_name="Эпиграф",
        blank=True,
        null=True,
    )

    email = models.EmailField(
        unique=True,
        verbose_name="Email",
        blank=True,
        null=True,
    )
    phone_number = models.CharField(
        max_length=25,
        verbose_name="Телефон",
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=35,
        verbose_name="Страна",
        blank=True,
        null=True,
    )
    address = models.CharField(
        max_length=50,
        verbose_name="Адрес",
        blank=True,
        null=True,
    )

    TEMPLATE_CHOICES = [
        ("description", "Описание ресторана"),
        ("services", "Перечень услуг"),
        ("contacts", "Контактная информация"),
        ("feedback", "Обратная связь"),
        ("history", "История"),
        ("mission", "Ценности и миссия"),
        ("team", "Наша команда"),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"
        # permissions = [('can_unpublish_product', 'Can unpublish product')]


class Table(models.Model):
    seats_amount = models.PositiveSmallIntegerField(verbose_name="Количество мест")
    is_reserved = models.BooleanField(verbose_name="Резерв", default=False)

    def __str__(self):
        return f"Столик № {self.pk}"

    class Meta:
        verbose_name = "Столик"
        verbose_name_plural = "Столики"

restaurant/views.py
from django.views.generic import DetailView

from restaurant.models import Page, Section


class SectionDetailView(DetailView):
    model = Section
    context_object_name = "section"

    TEMPLATE_MAP = {
        "О нас": "restaurant/main_description.html",
        "Команда": "restaurant/about_team.html",
        "Услуги": "restaurant/main_services.html",
        "История ресторана": "restaurant/about_history.html",
        "Миссия и ценности": "restaurant/about_mission.html",
        "Контактная информация": "restaurant/main_contacts.html",
        "Обратная связь": "restaurant/main_feedback.html",
        "На главную": "restaurant/welcome.html",
    }

    def get_template_names(self):
        section = self.get_object()
        return [f"{self.TEMPLATE_MAP.get(section.name)}"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context

restaurant/templates/restaurant/about_history.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

{% block content %}
<div class="card text-bg-dark">
    <div class="card-body">
        <h5 class="card-title">Наша история</h5>
        <p class="w-100 p-3 lh-base lighter">В тихом уютном дворике в одном из самых оживленных районов Москвы
            распахнул свои двери новый ресторан китайской кухни с необычной историей. Говорят, что его идея родилась в
            холодный зимний вечер, когда основатель, увлекавшийся кулинарией и старинными китайскими иллюстрациями,
            нашёл в старом шкафу карту местных кварталов и маленькую страницу с чернильной подписью: «Горизонты вкусов
            лежат за двориками».
            История начинается с встречи: молодой шеф-повар возвращался из командировки в провинцию Гуандун, где
            познакомился с мастерами мясной нарезки и умением раскатывать тесто до прозрачности. Он привёз домой не
            только рецепты, но и историю каждого блюда. В Москве он мечтал создать место, где люди будут не просто есть,
            а путешествовать в разные уголки Китая через ароматы, текстуры и мелодии в тарелке.
            Собрав маленькую команду друзей и единомышленников, он начал с преобразования старого дворика в уютное
            пространство. На кухне появился мастер старинной лепки пельменей и молодой повар, который нашёл удовольствие
            в сочетании местных продуктов с китайскими техниками. В интерьере произошла симфония деталей:
            каштановые полы, светильники в виде бумажных зонтов, зелёные растения, которые напоминают о долинах
            южного Китая, и настенные фолианты с иллюстрациями блюд и легенд.
            Хозяин ресторана начал сотрудничать с местными поставщиками: фермеры из Подмосковья, рыбаки из
            Черноморского побережья, биохудожники, которые выращивали зелень без химии. Роль дворика была не только в
            кухне и залах — это музыкальные вечера, где звучали гуцинь и флейта, сочетавшиеся с ароматами
            имбиря, чеснока и звуками жареного масла.
            С годами меню превратилось в карту путешествий, а ощущение уютной двориковой прохлады сочеталось с теплотой
            кухни и дружелюбной атмосферой обслуживания.
            Посетители рассказывали друг другу истории, связанные с их собственными двориками, и спокойствие, которое
            царило в зале, становилось символом того, что ресторан — это место, где любые города и эпохи могут
            встретиться за одной столешницей.
            Сегодня ресторан продолжает развиваться, сохраняя верность идее — каждое блюдо должно быть маленьким
            путешествием, каждая встреча — новым знакомством, а дворик — тихим пристанищем в шумном городе. Здесь
            страсть к китайской кулинарии сочетается с московским теплом и гостеприимством, чтобы гости уходили не
            просто сытыми, а вдохновлёнными новыми историями о вкусе и культуре.</p>
    </div>
    <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="card-img-bottom">
</div>

{% endblock %}

restaurant/templates/restaurant/about_mission.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

{% block content %}
<div class="card mb-3" style="max-width: 1200px;">
    <div class="row g-4">
        <div class="col-md-4">
            <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="img-fluid rounded-start">
        </div>
        <div class="col-md-8">
            <div class="card text">
                <div class="card-header fw-bolder w-75 p-3 fs-2">{{object.title}}</div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{object.content|linebreaks}}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

restaurant/templates/restaurant/about_team.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

{% block content %}
<div class="card mb-3" style="max-width: 1000px;">
    <div class="row g-4">
        <div class="col-md-4">
            <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="img-fluid rounded-start">
        </div>
        <div class="col-md-8">
            <div class="card text">
                <div class="card-header fw-bolder w-75 p-3 fs-2">{{ object.title }}</div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ object.content }}</li>

                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

restaurant/templates/restaurant/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title %}Мой ресторан{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% include 'restaurant/main_menu.html' %}
{% block content %}
{% endblock %}
<!--{% include 'restaurant/footer.html' %}-->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

restaurant/templates/restaurant/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            FinStore
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                 <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

restaurant/templates/restaurant/main_contacts.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>


{% block content %}
<div class="card mb-3" style="max-width: 1500px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="img-fluid rounded-start">
        </div>
    <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title text-center">{{ object.title }}</h5>
                <div class="container">
                    <div class="row text-start">
                        <div class="card text-center mb-4 box-shadow">
                            <div class="card-body">
                                <table class="table table-success table-striped">
                                    <tr>
                                        <td class="w-25">Страна</td>
                                        <td>{{ object.country }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">Телефон</td>
                                        <td>{{ object.phone_number }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">Адрес</td>
                                        <td>{{ object.address }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">Email</td>
                                        <td>{{ object.email }}/td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

restaurant/templates/restaurant/main_description.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

{% block content %}
<div class="card text-bg-dark">
  <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="card-img">
  <div class="card-img-overlay">
    <div class="card-body">
        <h3 class="w-75 p-3 card-title">{{ object.title }}</h3>
        <p class="w-75 p-3 lh-lg fw-bolder">{{ object.content }}</p>
    </div>
  </div>
</div>
{% endblock %}

restaurant/templates/restaurant/main_feedback.html
{% extends 'restaurant/base.html' %}


{% block content %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

<div class="card mb-3" style="max-width: 2200px;">
    <div class="row g-2">
        <div class="col-md-5">
            <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="img-fluid rounded-start">
        </div>
        <div class="col-lg-3 col-md-6 col-sm-16">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">{{object.}}</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

restaurant/templates/restaurant/main_menu.html
<ul class="nav nav-tabs">
    {% for page in pages %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ page.name }}</a>
        <ul class="dropdown-menu">
            {% if page.name == "Личный кабинет" %}
                {% if user.is_authenticated %}
                        <li>
                            <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                            {% csrf_token %}
                                <button type="submit" class="dropdown-item">Выйти</button>
                            </form>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'booking:manage_reservations' %}">Управление бронированием</a></li>
                        <li><a class="dropdown-item" href="{% url 'booking:reservation_history' %}">История бронирований</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:user_detail' user.pk %}">Мой профиль</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:user_update' user.pk %}">Редактировать профиль</a></li>
                        {% if perms.users.can_block_user %}
                            <li><a class="dropdown-item" href="{% url 'users:users_list' %}">Пользователи</a></li>
                        {% endif %}
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:register' %}">Зарегистрироваться</a></li>
                {% endif %}

            {% elif page.name == "Бронирование" %}
                <li><a class="dropdown-item" href="{% url 'booking:table_list' %}">Схема зала</a></li>
                {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'booking:reservation_create' %}">Забронировать столик</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'users:login' %}">Авторизуйтесь для бронирования</a></li>
                {% endif %}

            {% else %}
                {% for section in page.page_sections.all %}
                    <li><a class="dropdown-item" href="{% url 'restaurant:section_detail' pk=section.pk %}">{{ section.name }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    </li>
    {% endfor %}
</ul>

restaurant/templates/restaurant/main_services.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

{% block content %}
<div class="card mb-3" style="max-width: 2200px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="img-fluid rounded-start">
        </div>
        <div class="col-md-8">
            <div class="card text">
                <div class="card-header fw-bolder w-75 p-3 fs-2">{{object.title}}</div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"> {{ object.content|linebreaks }}</li>

                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

restaurant/templates/restaurant/welcome.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}{{ object.name }}{% endblock %}</title>

{% block content %}
<div class="card text-bg-dark">
  <img src="{{ MEDIA_URL }}{{ object.image.url }}" class="card-img">
  <div class="card-img-overlay">
    <p class="card-text fst-italic d-flex justify-content-lg-end">{{ object.epigraph|linebreaks }}</p>
    <div class="card-body">
        <h3 class="w-75 p-3 card-title">{{ object.title }}</h3>
        <p class="w-75 p-3 lh-base fw-bolder">{{ object.content|linebreaks }}</p>
    </div>
  </div>
</div>
{% endblock %}