config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("restaurant/", include("restaurant.urls", namespace="restaurant")),
    path("users/", include("users.urls", namespace="users")),
    path("booking/", include("booking.urls", namespace="booking")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (
    ConfirmationMessageView,
    CustomLoginView,
    UserDetailView,
    UserRegisterView,
    UserUpdateView,
    email_verification,
    UsersListView,
    UserBlockView,
)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "login/",
        CustomLoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path("<int:pk>/user/", UserDetailView.as_view(), name="user_detail"),
    path("<int:pk>/user/update/", UserUpdateView.as_view(), name="user_update"),
    path("confirm/", ConfirmationMessageView.as_view(), name="confirm"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/user/block/", UserBlockView.as_view(), name="user_block"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    name = models.CharField(
        max_length=35,
        verbose_name="Имя",
        blank=True,
        null=True,
        help_text="Укажите имя",
    )
    surname = models.CharField(
        max_length=35,
        verbose_name="Фамилия",
        blank=True,
        null=True,
        help_text="Укажите фамилию",
    )
    email = models.EmailField(unique=True, verbose_name="Email")

    avatar = models.ImageField(
        upload_to="avatars/",
        verbose_name="Аватар",
        blank=True,
        null=True,
        help_text="Загрузите свой аватар (необязательно)",
    )
    phone_number = models.CharField(
        max_length=25,
        verbose_name="Телефон",
        blank=True,
        null=True,
        help_text="Введите номер телефона (необязательно)",
    )
    country = models.CharField(
        max_length=35,
        verbose_name="Страна",
        blank=True,
        null=True,
        help_text="Введите страну (необязательно)",
    )
    token = models.CharField(
        max_length=100, verbose_name="Token", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", "Can block user"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class UserRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "name",
            "surname",
            "email",
            "avatar",
            "phone_number",
            "country",
            "password1",
            "password2",
        )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password1")
        password_confirm = cleaned_data.get("password2")

        if password and password_confirm and password != password_confirm:
            self.add_error("password2", "Passwords do not match")

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView

from config.settings import EMAIL_HOST_USER
from restaurant.models import Page

from .forms import UserRegistrationForm
from .models import User


class UserRegisterView(CreateView):
    form_class = UserRegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:confirm")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет! Перейди по ссылке {url} для подтверждения почты!",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    send_mail(
        subject="Добро пожаловать в наш ресторан",
        message="Спасибо, что зарегистрировались в нашем сервисе!",
        from_email=EMAIL_HOST_USER,
        recipient_list=[user.email],
    )
    return redirect(reverse("users:login"))


class CustomLoginView(LoginView):
    template_name = "users/login.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("users:user_detail", kwargs={"pk": self.request.user.pk})


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/user_detail.html"

    def get_object(self, queryset=None):
        user_to_view = super().get_object(queryset)
        user = self.request.user
        if user_to_view != user:
            raise PermissionDenied
        return user_to_view

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user
        context["image_path"] = "/static/images/account.jpg"
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserRegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_queryset(self, **kwargs):
        pk = self.kwargs.get("pk")
        user = get_object_or_404(User, pk=pk)
        if self.request.user != user:
            raise PermissionDenied
        return User.objects.filter(pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context


class ConfirmationMessageView(TemplateView):
    template_name = "users/confirm.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user

        return context


class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    template_name = "users/users_list.html"
    permission_required = "users.can_block_user"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["users"] = User.objects.all()
        context["pages"] = Page.objects.all()
        context["user"] = self.request.user
        return context


class UserBlockView(LoginRequiredMixin, View):
    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)

        if not request.user.has_perm("users.can_block_user"):
            return HttpResponseForbidden(
                "У вас нет прав для блокирования пользователя."
            )

        if request.user == user:
            return HttpResponseForbidden("Вы не можете заблокировать себя")

        else:
            user.is_active = False
            user.save()

        return redirect("users:users_list")

users/templates/users/confirm.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}Подтверждение регистрации{% endblock %}</title>

{% block content %}
        <h5>Для подтверждения регистрации перейдите по ссылке, которую мы отправили на ваш email.</h5>

{% endblock %}

users/templates/users/login.html
{% extends "restaurant/base.html" %}

{% block content %}
<h2>Вход</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
    <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'users:password_reset' %}">Забыли
        пароль?</a>

</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'restaurant/base.html' %}
{% block content %}
<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Добро пожаловать в сервис рассылки сообщений!</h5>
    </div>
</div>
<h1>Пароль изменен</h1>
<p>Поздравляем! Пароль для Вашего профиля успешно изменен. Используйте его для
    <a href="{% url 'users:login' %}">входа в систему</a>.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'restaurant/base.html' %}

{% block content %}

<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Добро пожаловать в сервис восстановления пароля!</h5>
    </div>
</div>
<h2>Новый пароль </h2>
<form method="post">
  {% csrf_token %}
  {% for f in form %}
  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
  <div class="form-error">{{ f.errors }}</div>
{% endfor %}
  <p><button type="submit">Сохранить</button></p>
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'restaurant/base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you
    entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and
    check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'restaurant/base.html' %}

{% block content %}

<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Добро пожаловать в сервис восстановления пароля!</h5>
    </div>
</div>
<h2>Восстановление пароля </h2>
<form method="post">
  {% csrf_token %}
  {% for f in form %}
  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
  <div class="form-error">{{ f.errors }}</div>
{% endfor %}
  <p><button type="submit">Сбросить по E-mail</button></p>
</form>
{% endblock %}

users/templates/users/register.html
{% extends "restaurant/base.html" %}
<title>{% block title %}Новый пользователь{% endblock %}</title>

{% block content %}
<h2>Регистрация</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
    {% if object %}
    <a href="{% url 'users:user_detail' user.pk %}" class="btn btn-secondary">Отмена</a>
    {% else %}
    <a href="{% url 'users:login' %}" class="btn btn-secondary">Отмена</a>
    {% endif %}
</form>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}Мой профиль{% endblock %}</title>
{% block content %}
<div class="card mb-3" style="max-width: 1100px;">
    <div class="row g-0">
        <div class="col-md-4">
            {% if object.avatar %}
            <img src="{{ MEDIA_URL }}{{ object.avatar.url }}" class="img-fluid rounded-start">
            {% else %}
            <img src="{{ MEDIA_URL }}{{ image_path }}" class="img-fluid rounded-start">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Мой профиль</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Имя: {{ object.name }}</li>
                <li class="list-group-item">Фамилия: {{ object.surname }}</li>
                <li class="list-group-item">Email: {{ object.email }}</li>
                <li class="list-group-item">Телефон: {{ object.phone_number }}</li>
                <li class="list-group-item">Страна: {{ object.country }}</li>
            </ul>
            <div class="card-body">
                <a class="icon-link" href="{% url 'users:user_update' object.pk %}">
                    Редактировать профиль
                    <svg xmlns="http://www.w3.org/2000/svg" class="bi" viewBox="0 0 16 16" aria-hidden="true">
                        <path d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                    </svg>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'restaurant/base.html' %}
<title>{% block title %}Список пользователей{% endblock %}</title>
{% block content %}
<div>
    <h4>Пользователи</h4>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Email</th>
        <th scope="col">Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row">{{object.pk}}</th>
        <td>
            <a class="card-link" href="{% url 'users:user_detail' object.pk %}">{{object.email}}</a>
        </td>
        <td>{{object.is_active|yesno:"Активен,Заблокирован" }}</td>
        {% if "users.can_block_user" in perms and object.is_active and request.user != object.email %}
        <th>
            <form action="{% url 'users:user_block' object.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Заблокировать</button>
        </form>
        </th>
               {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}